import assert from "node:assert/strict";
import test from "node:test";
import { claimProjectInvitation, hashProjectInvitationToken } from "./projectInvitationClaim";

const now = new Date("2026-08-12T12:00:00.000Z");
const fixture = (overrides: Record<string, unknown> = {}) => ({ id: "inv-1", inviteTokenHash: hashProjectInvitationToken("project-secret"), status: "Pending", cpAccountId: null, emailSnapshot: "contractor@example.com", expiresAt: new Date("2026-08-13T12:00:00.000Z"), inviteTokenExpiresAt: new Date("2026-08-13T12:00:00.000Z"), ...overrides });
function fakeClient(row: any, count = 1) { const calls: any[] = []; const invitation = { findUnique: async (args: any) => { calls.push(["findUnique", args]); return row; }, updateMany: async (args: any) => { calls.push(["updateMany", args]); return { count }; } }; return { calls, client: { contractorProjectInvitation: invitation } as any }; }

test("hashes token and claims matching pending invitation", async () => { const f = fakeClient(fixture()); const result = await claimProjectInvitation({ projectToken: "project-secret", accountId: "acct-1", accountEmail: " CONTRACTOR@example.com ", now, client: f.client }); assert.deepEqual(result, { ok: true, invitationId: "inv-1" }); assert.equal(f.calls[0][1].where.inviteTokenHash, hashProjectInvitationToken("project-secret")); assert.equal(f.calls[1][1].data.cpAccountId, "acct-1"); });
test("rejects invalid, expired, terminal, and mismatched email before mutation", async () => { for (const row of [null, fixture({ status: "Accepted" }), fixture({ expiresAt: new Date("2026-08-12T11:59:00Z") }), fixture({ inviteTokenExpiresAt: new Date("2026-08-12T11:59:00Z") }), fixture({ emailSnapshot: "other@example.com" })]) { const f = fakeClient(row); const result = await claimProjectInvitation({ projectToken: "project-secret", accountId: "acct-1", accountEmail: "contractor@example.com", now, client: f.client }); assert.equal(result.ok, false); assert.equal(f.calls.filter((x) => x[0] === "updateMany").length, 0); } });
test("same account is idempotent and another account cannot steal claim", async () => { const same = fakeClient(fixture({ cpAccountId: "acct-1" })); assert.deepEqual(await claimProjectInvitation({ projectToken: "project-secret", accountId: "acct-1", accountEmail: "contractor@example.com", now, client: same.client }), { ok: true, invitationId: "inv-1" }); const other = fakeClient(fixture({ cpAccountId: "acct-2" })); assert.deepEqual(await claimProjectInvitation({ projectToken: "project-secret", accountId: "acct-1", accountEmail: "contractor@example.com", now, client: other.client }), { ok: false, outcome: "already_claimed" }); });
test("lost CAS conflicts and performs no downstream writes", async () => { const f = fakeClient(fixture(), 0); const calls: string[] = []; const guarded = new Proxy(f.client, { get(target, prop, receiver) { if (["cpJob", "contractorAssignment", "cpOperatorEdge"].includes(String(prop))) calls.push(String(prop)); return Reflect.get(target, prop, receiver); } }); assert.deepEqual(await claimProjectInvitation({ projectToken: "project-secret", accountId: "acct-1", accountEmail: "contractor@example.com", now, client: guarded as any }), { ok: false, outcome: "conflict" }); assert.deepEqual(calls, []); });
