ALTER TABLE "Draw" ADD COLUMN "retainagePct" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "Draw" ADD COLUMN "lienWaiverDocId" TEXT;
ALTER TABLE "Draw" ADD COLUMN "lienWaiverReceived" BOOLEAN NOT NULL DEFAULT false;
